### ISSUE TITLE
Method chaining for objects

### ISSUE THREAD

**Issue by seferov** [iyzico/iyzipay-php#11]
I would like to use method chaining for objects. Example:
```php
$paymentCard = (new \Iyzipay\Model\PaymentCard())
	->setCardHolderName("John Doe")
	->setCardNumber("5528790000000008")
	->setExpireMonth("12")
	->setExpireYear("2030")
	->setCvc("123")
	->setRegisterCard(0)
	->setPaymentCard($paymentCard);
```

How about adding `return $this` to setters?

**Comment by sotuzun** [comment]
Hi @seferov , we don't want to use chaning in the client code. PaymentCardBuilder shall be the best option. But, this can create duplication in our code.
