### ISSUE TITLE
Install through Composer incomplete

### ISSUE THREAD

**Issue by FrancescoMussi** [iyzico/iyzipay-php#115]
Can you please check the installation of the package using Composer?

`composer require iyzico/iyzipay-php`

If I install the package using composer, the installation is not complete.
For instance it is missing the Subscription folder (Iyzipay/Request/Subscription):

https://github.com/iyzico/iyzipay-php/tree/master/src/Iyzipay/Request/Subscription

**Comment by byasarcse** [comment]
Hello @FrancescoMussi,

The composer exist in version v20.53,

Closing the issue due to timed out.
