### ISSUE TITLE
PayWithIyzico modelinde yer alan api url yanlış

### ISSUE THREAD

**Issue by serdarozturk** [iyzico/iyzipay-php#119]
Composer ile gelen son versiyonunda sorun var. Api url'i geçersiz. Geliştirme ortamındaki düzeltilmiş halini versiyonlayıp paketi güncellerseniz iyi olur. 

Gereksiz vakit kaybı oluştu.

**Comment by mehmetselim** [comment]
Selam @serdarozturk 

Güncellemeyi sağladık. 

Geri bildirim için çok teşekkürler.
