### ISSUE TITLE
 PayWithIyzico eksik method

### ISSUE THREAD

**Issue by serdarozturk** [iyzico/iyzipay-php#120]
Merhaba,

PayWithIyzico::retrieve ile dönen sonuçlar içinde api dökümanında bahsettiğiniz mdStatus'u alabileceğimiz bir method bulunmuyor. (PaymentResource)

https://dev.iyzipay.com/tr/iyzico-ile-ode/iyzico-ile-odeme-tamamlama

Ek olarak bu durumu sandbox ortamında nasıl deneyebiliriz? Dökümantasyonda belirtmemenize rağmen bir şekilde sandbox iyzico ile öde kısmına girebiliyoruz. (email@email.com - 123456) Sadece seçili kartı kullanabiliyorum. Yeni kartı nasıl yaratabiliriz diğer senaryolar için. (iyzico ile ödemeden 3ds'ye geçme, limit yetersiz v.s.)

Ek olarak ödeme kırılımımız için ürün adedi belirtemiyoruz sanırım? 

Bir de ufak bir öneri. IDE'ler için yorum satırına dönecek değerlerin tipini tanımlarsanız entegrasyon yapan yazılımcılar açısından daha verimli olur. 

<pre>
<code>
 /**
  *  @return PaymentItem[]
  */
  public function getPaymentItems()
  {
        return $this->paymentItems;
  }
</code>
</pre>

Teşekkürler

**Comment by serdarozturk** [comment]
Yeni kart yaratma çalıştı. Sadece mdStatus değeri alınamıyor rawResult içinden almak sağlıklı mı emin değilim.

**Comment by mehmetselim** [comment]
Selam @serdarozturk 

Evet, ürün adedi belirtemiyoruz. 
errorMessage boş değer döndüğü durumlar için rawResult üzerinden mdStatus değerini anlamlandırabilirsin. 
Bahsi geçen durumu değerlendirdikten sonra bir sonraki sürümlerde ekleyebiliriz. 

Değerli geri bildirimlerin için çok teşekkürler.
