### ISSUE TITLE
How to get the subscriptionReferenceCode?

### ISSUE THREAD

**Issue by FrancescoMussi** [iyzico/iyzipay-php#123]
For the API endpoints that concern subscriptions - retrieve, update, cancel subscription etc.. - the subscriptionReferenceCode is required.

I can easily see it in the dashboard - when I click to SUBSCRIPTIONS - Then click a item in the list - and in the Detail page I can see the reference code.

But the question is: How can I get it dynamically? In order to save it in the _User_ table and use it afterwards for API request?

**Comment by byasarcse** [comment]
Hello @FrancescoMussi,

SubscriptionReferenceCode is returning in the api response. After you initialize the payment form, you can retrieve the payment result using /v2/subscription/checkoutform/{{token}} endpoint. 

https://github.com/iyzico/iyzipay-php/blob/master/samples/subscription-samples/retrieve_subscription_checkout_form_result.php
