### ISSUE TITLE
Deprecation Notice: Class Iyzipay\Model\Mapper\Subscription\SubscriptionPricingplanMapper

### ISSUE THREAD

**Issue by afbora** [iyzico/iyzipay-php#128]
Iyzico PHP kütüphanesini (v2.0.47) Laravel projemde "Generating optimized autoload files" işleminden sonra artık aşağıdaki uyarıyı vermeye başladı. Daha önce vermiyordu.

> Deprecation Notice: Class Iyzipay\Model\Mapper\Subscription\SubscriptionPricingplanMapper located in /vendor/iyzico/iyzipay-php/src\Iyzipay\Model\Mapper\Subscription\SubscriptionPricingPlanMapper.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by mertkan1984** [comment]
Çözebildiniz mi

**Comment by afbora** [comment]
@mertkan1984 Hata değil de uyarı olduğu için detaylı incelemedim. `SubscriptionPricingplanMapper` kullanımında `plan` kelimesi küçük olarak kullanıldığından (`Plan` olarak kullanılması gerekiyor) PSR-4 standartlarına uymuyor, bu nedenle uyarı veriyor.

**Comment by cansozeri** [comment]
Çok basit bir şey bu kadar zamandır ele alınmaması ilginç, buraya bakan var mı acaba ??
