### ISSUE TITLE
Empty result

### ISSUE THREAD

**Issue by zilzurna** [iyzico/iyzipay-php#130]
Returned empty result while working on local server. By the way, there should be a debug option for Curl errors in this library.

Anyway, this is the error that returns with **curl_error ($ch)** in /Curl.php.

> SSL certificate problem: unable to get local issuer certificate

This solved my problem.
https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/31830614#31830614

**Comment by ShopskaSalad** [comment]
Hey @zilzurna. Thank you for your contribution. Happy merry coding! 🎅 ✌️
