### ISSUE TITLE
It will not autoload anymore in Composer v2.0 hatası

### ISSUE THREAD

**Issue by tanero** [iyzico/iyzipay-php#134]
composer update yapınca aşağıdaki gibi bir mesaj geliyor.

Deprecation Notice: Class Iyzipay\Model\Mapper\Subscription\SubscriptionPricingplanMapper located in C:/www/vendor/iyzico/iyzipay-php/src\Iyzipay\Model\Mapper\Subscription\SubscriptionPricingPlanMapper.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by halukakin** [comment]
composer 2 yayında artık. SubscriptionPricingPlanMapper'i kullananlara sorun yaratacaktır bu konu.
Dosya içinde class isminde camel case'de problem var. O yüzden autoload'a almıyor olabilir. `"SubscriptionPricingplanMapper"`

**Comment by sozgat** [comment]
Merhabalar,

Psr-4 ile ilgili release çıkılmıştır. Katkılarınız için teşekkürler.
