### ISSUE TITLE
Subscription functions always failed with API sandbox account

### ISSUE THREAD

**Issue by PREScriptZ** [iyzico/iyzipay-php#136]
I could not do any test with subscription functions, I copied your code with my API key & secret but always failed: https://github.com/iyzico/iyzipay-php/blob/master/samples/subscription-samples/create_customer.php & https://github.com/iyzico/iyzipay-php/blob/master/samples/subscription-samples/create_product.php

While I may create standard payment successfully with my API key & secret

Please check your subscription sandbox backend . Many thanks

**Comment by PREScriptZ** [comment]
Here's error:

`Iyzipay\Model\Subscription\SubscriptionProduct Object
(
    [name:Iyzipay\Model\Subscription\SubscriptionProduct:private] => 
    [description:Iyzipay\Model\Subscription\SubscriptionProduct:private] => 
    [referenceCode:Iyzipay\Model\Subscription\SubscriptionProduct:private] => 
    [productStatus:Iyzipay\Model\Subscription\SubscriptionProduct:private] => 
    [pricingPlans:Iyzipay\Model\Subscription\SubscriptionProduct:private] => 
    [createdDate:Iyzipay\Model\Subscription\SubscriptionProduct:private] => 
    [status:Iyzipay\IyzipayResource:private] => failure
    [errorCode:Iyzipay\IyzipayResource:private] => 100001
    [errorMessage:Iyzipay\IyzipayResource:private] => Sistem hatası
    [errorGroup:Iyzipay\IyzipayResource:private] => 
    [locale:Iyzipay\IyzipayResource:private] => 
    [systemTime:Iyzipay\IyzipayResource:private] => 1600401200088
    [conversationId:Iyzipay\IyzipayResource:private] => 
    [rawResult:Iyzipay\ApiResource:private] => {"status":"failure","errorCode":"100001","errorMessage":"Sistem hatası","systemTime":1600401200088}
)
`

**Comment by PREScriptZ** [comment]
If I change to production subscription endpoint, then error:

`Iyzipay\Model\Subscription\SubscriptionProduct Object
(
    [name:Iyzipay\Model\Subscription\SubscriptionProduct:private] => 
    [description:Iyzipay\Model\Subscription\SubscriptionProduct:private] => 
    [referenceCode:Iyzipay\Model\Subscription\SubscriptionProduct:private] => 
    [productStatus:Iyzipay\Model\Subscription\SubscriptionProduct:private] => 
    [pricingPlans:Iyzipay\Model\Subscription\SubscriptionProduct:private] => 
    [createdDate:Iyzipay\Model\Subscription\SubscriptionProduct:private] => 
    [status:Iyzipay\IyzipayResource:private] => failure
    [errorCode:Iyzipay\IyzipayResource:private] => 5
    [errorMessage:Iyzipay\IyzipayResource:private] => Doğrulama başarısız!
    [errorGroup:Iyzipay\IyzipayResource:private] => 
    [locale:Iyzipay\IyzipayResource:private] => tr
    [systemTime:Iyzipay\IyzipayResource:private] => 0
    [conversationId:Iyzipay\IyzipayResource:private] => 
    [rawResult:Iyzipay\ApiResource:private] => {"status":"failure","errorCode":"5","errorMessage":"Doğrulama başarısız!","locale":"tr","systemTime":0}
)
`

**Comment by byasarcse** [comment]
Hello @PREScriptZ,

Could you please reach out to destek@iyzico.com with the information of merchantId, request and response. 

Closing the issue due to timed out.

**Comment by hamitakti86** [comment]
@byasarcse i have same error in sandbox env. did you fix the problem once you connected to  destek@iyzico.com ?

**Comment by metecankiyici27** [comment]
@hamitakti86 This error can be received when the subscription is not active in your sandbox account. You can send an e-mail to destek@iyzico.com to activate the subscription in the test account.
