### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by tpaksu** [iyzico/iyzipay-php#139]
Hello, 

Can you please publish a revision release with the latest changes (with the 2 not so important commits), because composer started to warn us about the PSR-4 incompliant file. 

Regards.

**Comment by rizaergun** [comment]
Hello, please release the new version? All of our repos are getting PSR-4 errors.

Class Iyzipay\Model\Mapper\Subscription\SubscriptionPricingplanMapper located in ./vendor/iyzico/iyzipay-php/src/Iyzipay/Model/Mapper/Subscription/SubscriptionPricingPlanMapper.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by sozgat** [comment]
Hello,

We released a new version for psr-4. Thank you for your contribution.
