### ISSUE TITLE
composer 2 dump-autload hatası

### ISSUE THREAD

**Issue by huseyinyildirim** [iyzico/iyzipay-php#140]
Merhaba,

Slim Framework 3 ile yapılmış projemde composer 2 ile dump-autoload -o çalıştırdığımda aşağıdaki hatayı almaktayım.

`Class Iyzipay\Model\Mapper\Subscription\SubscriptionPricingplanMapper located in ./vendor/iyzico/iyzipay-php/src/Iyzipay/Model/Mapper/Subscription/SubscriptionPricingPlanMapper.php does not comply with psr-4 autoloading standard. Skipping.`

**Comment by huseyinyildirim** [comment]
Sorunu buldum. class adı ile dosya adındaki farklılıktan. SubscriptionPricingPlanMapper olması gerekirken SubscriptionPricingplanMapper yazılmış.

`<?php

namespace Iyzipay\Model\Mapper\Subscription;

use Iyzipay\Model\Subscription\SubscriptionPricingPlan;

class SubscriptionPricingplanMapper extends SubscriptionPricingPlanResourceMapper
{
    public static function create($rawResult = null)
    {
        return new SubscriptionPricingPlanMapper($rawResult);
    }

    public function mapSubscriptionPricingPlanFrom(SubscriptionPricingPlan $create, $jsonObject)
    {
        parent::mapSubscriptionPricingPlanResourceFrom($create, $jsonObject);

        return $create;
    }

    public function mapSubscriptionPricingPlan(SubscriptionPricingPlan $create)
    {
        return $this->mapSubscriptionPricingPlanFrom($create, $this->jsonObject);
    }
}`

**Comment by rizaergun** [comment]
Bununla ilgili gerekli değişiklikler master üzerinde yapılmış. Lütfen yeni bir release çıkar mısınız?

**Comment by sozgat** [comment]
Merhabalar,

Psr-4 ile ilgili release çıkılmıştır. Katkılarınız için teşekkürler.
