### ISSUE TITLE
How to get list of all transactions from the API

### ISSUE THREAD

**Issue by soprex** [iyzico/iyzipay-php#146]
In the PHP library, I can not find a way to get a list of all transactions for the merchant.
There is some description to get reports using SSH and CSV files. Is that the only option?

**Comment by sozgat** [comment]
Hello @soprex ,

You can get a list of all transactions only day by day. Use this file: https://github.com/iyzico/iyzipay-php/blob/master/samples/reporting_payment_transaction.php

For example: if you want to retrieve the last 30 days, you need to do a loop for days.

Thank you for your contribution.
