### ISSUE TITLE
Ödeme Form sonucu

### ISSUE THREAD

**Issue by omeryaman** [iyzico/iyzipay-php#147]
ödeme formu sonucunda dosyalarda yer alan örnek kod ile https://dev.iyzipay.com/tr/odeme-formu/odeme-formu-sonucu buradaki parantez içinde olmayan değerleri elde edebiliyorum ancak paymentTransactionId (ItemTransactions) den sonrasını örnek kod ile elde edemiyorum bunun gibi parantez içindeki değerleri nasıl bir kodla alabilirim?

**Comment by sozgat** [comment]
Merhaba @omeryaman ,

Form sonucunu https://github.com/iyzico/iyzipay-php/blob/master/samples/retrieve_checkout_form_result.php adresindeki gibi alabilirsiniz.

Api üzerinden geçen ödemelerinizde ise https://github.com/iyzico/iyzipay-php/blob/master/samples/retrieve_payment_result.php adresindeki örnek üzerinden paymentId ile ödeme sonucunu alabilirsiniz. Daha fazla bilgi için https://dev.iyzipay.com/tr/api/odeme-sorgulama adresini ziyaret edebilirsiniz.

İyi günler dilerim.
