### ISSUE TITLE
Class Iyzipay\Model\Mapper\Subscription\SubscriptionPricingplanMapper located in ./vendor/iyzico/iyzipay-php/src/Iyzipay/Model/Mapper/Subscription/SubscriptionPricingPlanMapper.php does not comply with psr-4 autoloading standard.

### ISSUE THREAD

**Issue by BackendDevops** [iyzico/iyzipay-php#150]
```
namespace Iyzipay\Model\Mapper\Subscription;

use Iyzipay\Model\Subscription\SubscriptionPricingPlan;

class SubscriptionPricingplanMapper extends SubscriptionPricingPlanResourceMapper
{
    public static function create($rawResult = null)
    {
        return new SubscriptionPricingPlanMapper($rawResult);
    }
```

olması gereken 

```
namespace Iyzipay\Model\Mapper\Subscription;

use Iyzipay\Model\Subscription\SubscriptionPricingPlan;

class SubscriptionPricingPlanMapper extends SubscriptionPricingPlanResourceMapper
{
    public static function create($rawResult = null)
    {
        return new SubscriptionPricingPlanMapper($rawResult);
    }
```
**SubscriptionPricingplanMapper** class isminde pascal case olmadığı için psr-4 hatası alıyoruz.
**SubscriptionPricingPlanMapper** olması gerekiyor
Laravel paketi olarak kullanıyoruz. Vendor dosyasında güncelleme yapmak istemiyoruz.
  Bu konu ile ilgili nasıl bir güncelleme yapılabilir

**Comment by rizaergun** [comment]
Selam, bu konu aslında master branch üzerinde çözülmüş. Lütfen yeni bir release çıkabilir misiniz?

**Comment by yedincisenol** [comment]
Selamlar. Konuda bir gelişme var mıdır?

**Comment by BackendDevops** [comment]
@yedincisenol  maalesef master branch içinde çözülmüş olsa da yeni bir release çıkmadılar henüz

**Comment by sozgat** [comment]
Merhabalar,

Ben said, iyzico geliştirici ekibindeyim. Master branch üzerinden release çıkılmıştır. Değerli geri bildirimleriniz için teşekkürler.

İyi günler dilerim.
