### ISSUE TITLE
ödeme detaylarına ulaşabileceğimiz endpoint var mı?

### ISSUE THREAD

**Issue by alikopasa** [iyzico/iyzipay-php#151]
merhaba,

ben bir ödemenin detaylarına ulaşmak istiyorum, kişi detay bilgisine ve ürünlere yani.
bunu sağlayabilecek bir endpoint var mı acaba?

teşekkürler.

**Comment by eka7a** [comment]
https://github.com/iyzico/iyzipay-php/blob/master/samples/retrieve_payment_result.php
