### ISSUE TITLE
Kart Silme Çalışmıyor.

### ISSUE THREAD

**Issue by eka7a** [iyzico/iyzipay-php#153]
Gerçek ortamda test etmedim ancak sandbox üzerinde kart silme çalışmıyor.

samples/delete_card.php çalıştırıldığında boş sonuç dönüyor.

**Comment by sozgat** [comment]
Merhaba @eka7a,

Snadbox ortamında kontrolleri sağladığımızda kart oluşturup, daha sonra kayıtlı kartı silme işlemi gerçekleştirdik. Servisin çalışmasında herhangi bir problem görünmemektedir. 

Geri bildiriminiz için teşekkür ederiz.

**Comment by eka7a** [comment]
Merhaba
Zaten kart ekleme de ve listelemede bir sorun yok. Silme isteğinde hiçbir şey dönmüyor.
Burada yayınladığınız saf kütüphane dosyaları üzerinde videolu olarak gösteriyorum. Arada başka bir yazılım yok.

samples/config.php içine sandbox api keyleri eklendi.
localhostta olduğu için post isteğine **CURLOPT_SSL_VERIFYPEER => false** eklendi.

https://epiksel.net/sandbox-iyzico.mp4

**Comment by sozgat** [comment]
Merhaba @eka7a,

İlgili servisi kontrol ettiğimizde servisin başarılı bir şekilde çalıştığı görülmektedir. Tekrardan kontrol edebilir misiniz ?

Teşekkürler.

**Comment by eka7a** [comment]
Merhaba @sozgat,
Aynı sorun devam ediyor. Benim sandbox hesabımla ilgili bir durum olabilir mi?
