### ISSUE TITLE
Adet seçeneği

### ISSUE THREAD

**Issue by aktolu** [iyzico/iyzipay-php#156]
Sipariş oluştururken birdan fazla aynı ürün eklemek istersek izlememiz gereken yol, her adet için ayrı ürün mü eklemektir?

**Comment by AyhanDelican** [comment]
Bu sorunun cevabını ben de merak ediyorum.

**Comment by borakayalar** [comment]
Anladığım kadarı ile 

$basketItems = [];
$item = new \Iyzipay\Model\BasketItem();
$item->setId("BI101");
$item->setName("Binocular");
$item->setCategory1("Collectibles");
$item->setCategory2("Accessories");
$item->setItemType(\Iyzipay\Model\BasketItemType::PHYSICAL); // veya 
// $item->setItemType(\Iyzipay\Model\BasketItemType::VIRTUAL);
$item->setPrice("0.3");
$basketItems[] = $item;

$request->setBasketItems($basketItems);

Bu şekilde birden fazla item o $basketItems array' ıne push edebilirsiniz.

**Comment by byasarcse** [comment]
Merhabalar,

Örnek bir sepet kurgusunu aşağıda sample olarak paylaşıyorum. Sepette birden fazla ürünü sample dosyada olduğu gibi gönderebilirsiniz. 

https://github.com/iyzico/iyzipay-php/blob/master/samples/create_payment.php

**Comment by yalcinozer** [comment]
2022'den beri IYZICO'yu kullanan biri olarak bu senaryoyu benden merak ettim. Soruyu ilk soran arkadaşa tebrikler, ancak verdiğiniz cevap hem geç, hem soruyu karşılamıyor. Profesyonellik diplerde. Soru şu; aynı üründen 2-3 tane eklerken, ayrı ayrı eklemek yerine `quantity` gibi bir alan ile direk miktar girilse nasıl olurdu?
