### ISSUE TITLE
3DS Secure Kullanımı Hakkında

### ISSUE THREAD

**Issue by neetkiss** [iyzico/iyzipay-php#161]
Kodlarla mevcut sistemime bir alt yapı hazırlıyorum. Fakat 3ds Secure hakkında bir yer göremedim. 3ds için nasıl bir çalışma yapabilirim ?

**Comment by neetkiss** [comment]
Güncel

**Comment by byasarcse** [comment]
Merhabalar @neetkiss ,

Konuya ilişkin olarak güncel dökümanımızı inceleyebilirsiniz.
https://docs.iyzico.com/odeme-metotlari/3ds
