### ISSUE TITLE
iyzico da ödemenin sonucunu nasıl kontrol edebilirim?

### ISSUE THREAD

**Issue by FatihKaya-kafgame** [iyzico/iyzipay-php#162]
İyzico'yu Laravel'de entegre ettim, test kartlarıyla test ettiğimde ödemenin başarılı olduğunu görüyorum ama geriye bunu döndürüp ekranda başarılı diye gösteremiyorum. Bazı kodlar buldum, 

"
          $request = new \Iyzipay\Request\RetrieveCheckoutFormRequest();
          $request->setLocale(\Iyzipay\Model\Locale::TR);
          $request->setConversationId("123456789");
          $request->setToken($_POST['token']);

          $checkout= \Iyzipay\Model\CheckoutForm::retrieve($request, $options);
          print_r($checkout);
"

burada ekranda gelen sonuçlar içerisinde paymentStatus da gözüküyor fakat sadece paymentStatus'u çekemiyorum.
Nasıl yapabilirim? Yardımcı olabilir misiniz?

**Comment by neetkiss** [comment]
`$checkout->getResponse();`
veya
`$checkout->getRawResult();`
kullanabilirsin. json decode ile de parçalayabilirsin. İlaveten status değerini sana post olarak da gönderiyor.

**Comment by byasarcse** [comment]
Merhabalar @FatihKaya-kafgame,

Checkoutform Entegrasyon dökümanımızı aşağıdaki gibi iletiyorum.
https://docs.iyzico.com/odeme-metotlari/odeme-formu

Ek sorularınız için destek@iyzico.com ile iletişime geçebilirsiniz.
