### ISSUE TITLE
paymentTransictionId erişemiyorum

### ISSUE THREAD

**Issue by yasin172** [iyzico/iyzipay-php#164]
Merhaba, ben Iyzico API ile siteme pazaryeri ödeme entegrasyonu kurmaya çalışıyorum fakat ödemelerin paymentTransictionId'lerine erişemiyorum. 

            foreach ($checkoutForm->getPaymentItems() as $key => $item) {
                $cart_[$key]->paymentTransactionId = $item->paymentTransactionId;
            }

Kullandığım kod bu şekilde aldığım hata ise private object'in içine erişemezsiniz.

Yardımcı olabilirseniz çok sevinirim, teşekkürler iyi günler.
****

**Comment by umutkorkmaaz** [comment]
https://github.com/iyzico/iyzipay-php/issues/173#issuecomment-1551531973
