### ISSUE TITLE
cURL https sorunu

### ISSUE THREAD

**Issue by borakayalar** [iyzico/iyzipay-php#166]
**DefaultHttpClient.php** içerisinde yer alan curl isteğine ait curl parametreleri içerisinde bulunmayan ama bulunması gereken
**CURLOPT_SSL_VERIFYHOST**, **CURLOPT_SSL_VERIFYPEER** parametreleri eklenmeli ve config class' ı üzerinden api key' in set edilmesi gibi ssl verify işlemi için ilettiğim parametreler **SSL_VERIFY** gibi bir config parametresi üzerinden true false olarak set edilebilmeli.

Çünkü localhost dışında sanal ama localde çalıştığımız hostlar için https üzerinden cURL istekleri çalışmıyor.

Örneğin ;

    public function get($url)
    {
        return $this->curl->exec($url, [
            CURLOPT_CUSTOMREQUEST  => "GET",
            CURLOPT_RETURNTRANSFER => TRUE,
            CURLOPT_VERBOSE        => FALSE,
            CURLOPT_HEADER         => FALSE,
            CURLOPT_SSL_VERIFYHOST => !config('DEVELOPMENT'), //ssl verify parameters added
            CURLOPT_SSL_VERIFYHOST => !config('DEVELOPMENT'), //ssl verify parameters added
        ]);
    }

için bu şekilde repo yu editlemek durumunda kaldım. Kendi config helper'ım farklı bir yapıda olduğu için config class'ı na dokunmadım.

Eğer localda cURL ile sorun yaşayan olursa http methodları için bu iki parametreyi ekleyebilirler.
https://sandbox.... yerine http://sandbox... yaptığınızda iyzico kısmı da sayfa bulunamadı cevabı dönüyor.

**Comment by borakayalar** [comment]
Kesinlikle local bir cert dosyasi ile cozulebilir. Fakat ayni makinede bircok php versiyonu ile gelistirme yapanlar icin her seferinde local websunucu icin bu dosyayin yerlestirilmesi gerekiyor. Benim dev ortamimda ihtiyacim geregi ne yazik ki wamp ayri var laragon ayri var vscode uzerinden bazen php serve ediyorum vs… o yuzden opsiyonel bir parametreye baglanmasini tabsiye etmistim

**Comment by byasarcse** [comment]
Merhabalar,

Geri bildiriminiz için teşekkürler, konu ekiplerimize iletilmiştir. Ek destek talepleriniz için destek@iyzico.com ile iletişime geçebilirsiniz.
