### ISSUE TITLE
Sessionlar siliniyor 

### ISSUE THREAD

**Issue by EmirAKSOY1** [iyzico/iyzipay-php#170]
iyzico nun ödeme ekranında session problemsiz görülüyor .  Ancak callback sayfasında yani sonuc sayfasında sessionlara ulaşamıyorum ve bu bazen oluyor bazen problemsiz görülüyor bazen görülmüyor .
iyzico ödeme ekranında her zaman görülüyor .

**Comment by EmirAKSOY1** [comment]
`session_start();
ob_start();
require_once('iyzico/config.php');
include("db.php"); 
print_r($_SESSION);`

**Comment by EmirAKSOY1** [comment]
session_start();
ob_start();
require_once('iyzico/config.php');
include("db.php"); 
print_r($_SESSION);

**Comment by byasarcse** [comment]
Merhabalar @EmirAKSOY1 ,

Bahsettiğiniz sorun same site ile ilişkili görülmektedir, aşağıdaki linki takip ederek uygulamanızı rica ederiz. Ek sorularınız olması durumunda destek@iyzico.com iletişime geçebilirsiniz. 

https://dev.iyzipay.com/tr/sss/samesite-problemi-nedir

**Comment by EmirAKSOY1** [comment]
6 ay sonra cevap verdiginiz için çok teşekkür ederim

11 Ağu 2023 Cum 11:36 tarihinde Bünyamin Yaşar ***@***.***>
şunu yazdı:
