### ISSUE TITLE
TransactionId değerine ulaşamıyorum.

### ISSUE THREAD

**Issue by cagdaskarabudak** [iyzico/iyzipay-php#173]
Merhaba, Ödeme işlemini geri alabilmek için, ödeme esnasında ödeme bilgilerini veri tabanıma kaydetmem gerekiyor.
Geri ödeme işlemi için benden istenen transaction id değerine bir türlü ulaşamıyorum.

        $payment = Payment::create($request, $options);

        //try 1
        $transactionID = $payment->getPaymentTransactionId();
//error:
    //Call to undefined method Iyzipay\Model\Payment::getPaymentTransactionId()

        //try 2
        $transactionID = $payment->paymentTransactionId();
//error:
    //Call to undefined method Iyzipay\Model\Payment::paymentTransactionId()

**Comment by cagdaskarabudak** [comment]
```
    //Payment işlemi yapılıyor.
        $payment = Payment::create($request, $options);

    //Payment işleminde sepette bulunan ürünleri çektiriyorum.
        $paymentItems= $payment->getPaymentItems();

    //Payment işleminde sepette bulunan ürünlerden 1. ürünün transaction id değerini alıyorum.
        $item1TransactionId = $paymentItems[0]->getPaymentTransactionId();
```

Bu şekilde çözüme ulaşıldı. Hayırlı fixler :)

**Comment by byasarcse** [comment]
Merhabalar @cagdaskarabudak,

Konu çözüldüğü için issue'yu kapatıyoruz.
