### ISSUE TITLE
SubscriptionUpdatePricingPlanRequest does not contain Price update option

### ISSUE THREAD

**Issue by boraerciyas** [iyzico/iyzipay-php#178]
Merhaba,

SubscriptionUpdatePricingPlanRequest ile Price ve PaymentInterval'ı değiştirmek istiyorum fakat bu alanları değiştiremiyorum. 

Subscription'da Price ve Payment Interval'ı güncellemenin yöntemi nedir acaba?

**Comment by byasarcse** [comment]
Merhabalar @boraerciyas,

Abonelik işlemleri için öncelikle aboneliğin başlatılacağı bir ürün , ardından bir ödeme planı oluşturmanız gerekmektedir. Ödeme planını oluşturduktan sonra kredi kartı ile ödeme alarak aboneliği başlatabilirsiniz.

Mevcut bir abonelikteki fiyatı değiştirebilmek için yeni bir ödeme planı oluşturmalı ve aboneliği yeni ödeme planına upgrade etmeniz gerekmektedir.

Yeni ödeme planı oluşturma örnek requesti :
https://github.com/iyzico/iyzipay-php/blob/master/samples/subscription-samples/create_pricing_plan.php

Abonelik upgrade örnek requesti :
https://github.com/iyzico/iyzipay-php/blob/master/samples/subscription-samples/upgrade_subscription.php#L10

Abonelik dökümanı :
https://dev.iyzipay.com/tr/subscription 

Not:Upgrade fonksiyonun içerisinde UpgradePeriod parametresi bulunmaktadır."NOW" ve "NEXT_PERIOD"değerlerini alabilmektedir.

NOW -->Sorgu sırasında upgrade işleminin hemen gerçekleştirilmesini 
NEXT_PERIOD -->Aboneliğin çekileceği zaman ilgili güncellemenin yapılacağını belirtmektedir.

Ek sorularınız için destek@iyzico.com üzerinden bizler ile iletişime geçebilirsiniz.
