### ISSUE TITLE
Sepet kırılım fiyatı, hesaplamalar, kargo fiyatı vb. koşullarda?

### ISSUE THREAD

**Issue by muratunal** [iyzico/iyzipay-php#34]
Merhabalar,

Diyelim ki elimizde A ürünü var. Fiyatı 79 TL. Bir diğer ürünümüz de B olsun ve yine fiyatı 79 TL fakat x opsiyonu ile eklendiğinde (+5 TL ) fiyatı 84 TL oluyor. 

Sepetimizde Ara toplamımız 163 TL oldu. Diyelim ki 200 TL altı alışverişlerde sabit 5 TL kargo uygulamamız var. Böylelikle sepetimiz 168 TL oldu.

Merak ettiğim husus;
- requeste hangi price ve paid price 'ı set etmeliyiz?
- setBasketItems içine gönderdiğimiz her bir item için fiyatı kaça set etmeliyiz?

Devamlı sepet kırılımı ile ilgili failure mesajını almaktayım.

Teşekkürler

**Comment by sotuzun** [comment]
Merhaba,
Bu bir php client issue'su değildir. entegrasyon [at] iyzico.com adresine bu tarz sorularınızı yollayabilirsiniz.
