### ISSUE TITLE
DefaultHttpClient missing curl parameters

### ISSUE THREAD

**Issue by kodlayici19** [iyzico/iyzipay-php#37]
When i use or test the php client for local environments (for me), http requests doesn't work as expected. No response is return from api server.

When i examine the code, found missing parameters for curl in DefaultHttpClient.php file. Perhaps the CURLOPT_SSL_VERIFYHOST and CURLOPT_SSL_VERIFYPEER parameters must set false for local using.

My environment:
Server: IIS 7.0
PHP: PHP for IIS 5.6.0

İngilizce için kusura bakmayın. :)

**Comment by sotuzun** [comment]
Please, relate to this articles

http://snippets.webaware.com.au/howto/stop-turning-off-curlopt_ssl_verifypeer-and-fix-your-php-config/
https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html

Check the warning section. If you get an empty response, check you php configs or set CURLOPT_SSL_VERIFYPEER to false locally.
