### ISSUE TITLE
readme örneği ile alakalı

### ISSUE THREAD

**Issue by yerlikayao** [iyzico/iyzipay-php#38]
Selamlar,

Readme örneği denendiğinde çalışmıyor sanırım update gerek "readme.md" için 

PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Iyzipay\Model\Payment::create() 

içinde Payment modelinde create static methodunu da göremedim açıkcası belki ben birşeyleri gözden kaçırıyorumdur fakat bunu aradıgımda examples folder'da da yok buradaki Readme.md örneği

**Comment by sotuzun** [comment]
Selam Onur,
https://github.com/iyzico/iyzipay-php/blob/master/samples/create_payment.php
Sample klasörünü inceledin mi?

**Comment by yerlikayao** [comment]
bendeki version
"iyzico/iyzipay-php":"~1.0.8",

olduğu için farklılıklar var son versiyona güncelleyince düzelir. 

deprecated olan versionları belirtmek daha efektif olabilir belki composer install komutunda
