### ISSUE TITLE
Iyzipay\Model\Payment::create() fonskiyonunda tüm değerler Null dönüyor.

### ISSUE THREAD

**Issue by erhankilic** [iyzico/iyzipay-php#43]
Usage kısmında belirtildiği üzere tüm değerleri girerek request oluşturma fonksiyonunu çalışyırıyorum ama sonucunda paymentId dahil tüm her şey null olarak dönüyor.
var_dump() ile $request'i debug ettiğimde tüm verilerin uygun biçimde yerleştiğini gördüm.
create() fonksiyonunun içindeki $rawResult'u var_dump() ile debug ettiğimde false döndürdü.

Teşekkürler.

**Comment by sotuzun** [comment]
Please refer to #37
