### ISSUE TITLE
What is ErrorCode 1001 "Api Bilgileri Bulunamadı"?

### ISSUE THREAD

**Issue by bulentgercek** [iyzico/iyzipay-php#46]
All the request information sent properly but i am taking that response back :

Iyzipay\Client\Ecom\Payment\Response\EcomPaymentCheckoutFormInitializeResponse::__set_state(array(
   'token' => NULL,
   'checkoutFormContent' => NULL,
   'tokenExpireTime' => NULL,
   'rawResult' => '{"status":"failure","errorCode":"1001","errorMessage":"api bilgileri bulunamadı","locale":"tr","systemTime":1486938124223,"conversationId":"58a0e00bbe06f_228"}',
   'status' => 'failure',
   'errorCode' => '1001',
   'errorMessage' => 'api bilgileri bulunamadı',
   'errorGroup' => NULL,
   'locale' => 'tr',
   'systemTime' => 1486938124223,
   'conversationId' => '58a0e00bbe06f_228',
))

Please explain what is error code 1001. I didn't find it on api documentation.

**Comment by sotuzun** [comment]
This is the deprecated client. Please use iyzipay-php. Could you please send this question to entegrasyon@iyzico.com.
