### ISSUE TITLE
Woocommerce plugin php7 error

### ISSUE THREAD

**Issue by eminozlem** [iyzico/iyzipay-php#47]
Warning: Declaration of Iyzipay\Client\Ecom\Payment\Response\Mapper\EcomPaymentCheckoutFormInitializeResponseMapper::mapResponse(Iyzipay\Client\Ecom\Payment\Response\EcomPaymentCheckoutFormInitializeResponse $response, $jsonResult) should be compatible with Iyzipay\Client\ResponseMapper::mapResponse(Iyzipay\Client\Response $response, $jsonResult) 

wp-content/plugins/iyzico-woocommerce-checkout-form/src/Iyzipay/Client/Ecom/Payment/Response/Mapper/EcomPaymentCheckoutFormInitializeResponseMapper.php on line 8

**Comment by yyenigun** [comment]
The client you used is deprecated and is not maintained. Please use client on Github. (i.e.: iyzipay-php)

**Comment by eminozlem** [comment]
Current wooocommerce module is 1.0.6 which is the same as installed on site. I couldnt see any __ResponseMapper class under iyzipay-php

**Comment by kurtulussahin** [comment]
You can remove "client" folder in .../wp-content/plugins/iyzico-payment-module/src/Iyzipay
the "client" folder is a part of deprecated version.

**Comment by eminozlem** [comment]
Seems like it's still used.
I get  
Warning: require(src/Iyzipay/Client/Configuration/ClientConfiguration.php): failed to open stream: No such file or directory in public_html/wp-content/plugins/iyzico-woocommerce-checkout-form/IyzipayBootstrap.php on line 167

if i remove / rename the "Client" folder.

If I comment out that line it takes a turn for the worse - stack erorrs etc.

Am I the only one using the WooCommerce module for iyzico on a PHP7 install ? I wonder why this isn't fixed yet.. the current version( 1.0.6) of WooCommerce module is 1 year old

**Comment by kurtulussahin** [comment]
You can download uptodate version of plugin via wordpress marketplace

**Comment by eminozlem** [comment]
OK, we have established its a php7 issue with the module, and informed them to fix it, i guess i should close the topic.
