### ISSUE TITLE
I am getting 1000 Geçersiz İmza Error

### ISSUE THREAD

**Issue by veyselsahin** [iyzico/iyzipay-php#48]
I am getting 1000 "geçersiz imza" error but cannot see why I am getting this error on CreateCheckoutFormInitializeRequest.
I am sending price with dot(.) as decimal seperator like 14.90

**Comment by sotuzun** [comment]
This question is related to integration. Please send your question to entegrasyon at iyzico.com. I'm closing it.

**Comment by erata** [comment]
Bu hatayı ben de aldım. Sistem çalışıyordu normal bir şekilde. ne olduysa son zamanlar bu hatayı almaya başladım. Kod aynı kod ama çalışmıyor.

> com.iyzipay.model.ThreedsInitialize@2683dd61[
>   htmlContent=<null>
>   status=failure
>   errorCode=1000
>   errorMessage=Geçersiz imza
>   errorGroup=<null>
>   locale=tr
>   systemTime=1507902397231
>   conversationId=6156
> ]

**Comment by veyselsahin** [comment]
@erata ben hatayı inputların hepsini silip iyziconun döküman sayfasındaki örnekle değiştirdim. Sonra tekrardan kendime göre düzenlemiştim. Ama hangisinden kaynaklı olduğunu anlamamıştım. Sen de öyle yaparak çözebilirsin.

**Comment by erata** [comment]
@veyselsahin sağolasın, benimki zaten çalışan bir örnekti. En kötü ihtimal dediğiniz yöntemden gidecem.

**Comment by veyselsahin** [comment]
@erata aslında şöyle birşey olmuş olabilir mi bilemedim şimdi. Aklımda kaldığı kadarıyla söylüyorum o problem gönderdiğimiz para formatıyla alakalı olabilir. Yani 15,00 veya 15.00 gibi birşey olabilir. Gönderdiğiniz datadan kaynaklı da olabilir şimdi öyle deyince aklımda geldi dediğim ilk yöntemi denemeden önce bunu denerseniz belki biraz zaman kazandırabilir. Kolay gelsin.

**Comment by erata** [comment]
@veyselsahin ben java kullanıyorum ve mevcut örneklerde 

> setPrice(new BigDecimal(price))
 price float bi değerdi ve hata almıyordum bu kullanımdan.
 
farklı şekillerde denicem artık.
tekrar sağolasın.

**Comment by veyselsahin** [comment]
ben bu hatayı yıllar sonra başka sistemde yeniden aldım ama bu aptal herifler hala açıklayıcı bir mesaj dönmeyi becerememişler.

**Comment by AlperenElbasan** [comment]
Ben de aynı hatayı aldım şimdi, kullanıcının last login date ve registration date'lerde gönderdiğim tarih formatından dolayı olmuş.

Tavsiyem @veyselsahin 'inin taktiğini  uygulayıp, örnekteki koddan yola çıkıp yavaş yavaş değiştirirek patladığı noktayı bulmanız.

**Comment by selimata** [comment]
Aynı hatayı ben de aldım, sorun sistemin beklediği type'ta değer gönderilmemesinden kaynaklanıyor. Daha açıklayıcı bir hata mesajı dönülmesi daha iyi olurdu.

**Comment by tolgakurtarmis** [comment]
Bende de aynı hatayı veriyordu request.CallbackUrl sildiğimde düzeldi denemenizi tavsiye ederim

**Comment by tanero** [comment]
Hata mesajının daha açıklayıcı olmasında fayda var, eğer hata oluşuyorsa demekki post edilen data ile sistemin beklentisinde bir uyuşmama durumu var.

**Comment by atakanozgurr** [comment]
CallbackUrl , 3d ile ödeme için girilebilir ama 3d siz ödeme için girilemiyor bu yüzden hata veriyor. Ayrıca callbackurl için localhost yerine başka bi url deneyebilirsiniz.

**Comment by oguzhancelikarslan** [comment]
TC kimlik no veya şehir parametrelerini göndermediğinizde de böyle hatalar alabilirsiniz. Eksik alan gittiğinde bu şekilde bir hata dönüyor.

**Comment by enesyurtlu** [comment]
Merhabalar öncelikle bilgilendirme için yazıyorum. Bu hatanın alındığı durumlarda şunları kontrol ediniz:
- Kullanıcı bilgilerinin eksiksiz olduğundan emin olunuz
- `Shipping` ve `Billing` adres bilgilerini eksiksiz gönderdiğinizden emin olunuz
- Fiyat bilgisini `100.00` (kuruş bilgisi nokta ile ayrılmalı)
- `Laravel` kullanıyorsanız registration_date bilgisi için `created_at` sütununu kullanıyorsanız bu değerin `Laravel`'den `Carbon` kütüphanesinin modeli şeklinde dönüş yaptığı için hata alıyor olabilirsiniz. Bunu düzeltmek için şu şekilde yazabilirsiniz: `\Carbon\Carbon::parse($user->created_at)->format("Y-m-d h:i:s")`
Hata aldığınızda gönderdiğiniz bilgileri `console.log()` , `var_dump()` ya da `dd()` yapıp kontrol ederseniz hangi bilgileri eksik gönderdiğinizi bulup düzeltebilirsiniz.

**Comment by hasanmuzak** [comment]
Bir çözüm de ben önereyim;

Fiyat bilgisini 2 decimal yuvarlamadığımızda bu hata ile karşılaştım.

Örn : 

29.432 -> Hatalı
29.43 -> Doğru

Umarım iyzipay ekibi hatanın sebebini dönen yanıta basar. Çünkü dökümanda yazmayan bir çok noktayı deneye deneye öğrenmek zorunda kalıyoruz.

**Comment by adnankaya** [comment]
`gsmNumber: ""` gönderildiğinde de bu hata alınıyor.

**Comment by ashrafyawar** [comment]
callback parametresini ekleyince bu hatayi aldim bende, bunun bi cozumu var mi? 3D kullanmak icin callback parametlesi lazim ama onu ekleyincede calismiyor...

**Comment by arslansahin** [comment]
Veriler aşağıdaki sırada gönderilmediğinde geçersiz imza hatası veriyor.

{
  "locale": "tr",
  "conversationId": "12345",
  "price": "2.1",
  "paidPrice": "2.1",
  "installment": 1,
  "basketId": "123456",
  "paymentCard": {
    "cardHolderName": "John Doe",
    "cardNumber": "5528790000000008",
    "expireYear": "2030",
    "expireMonth": "12",
    "cvc": "123"
  },
  "buyer": {
    "id": "123",
    "name": "Arslan",
    "surname": "Sahin",
    "identityNumber": "11111111111",
    "email": "iletisim@nsoft.com.tr",
    "registrationAddress": "Adres Bilgileri",
    "city": "Bursa",
    "country": "Turkey",
    "ip": "78.173.65.219"
  },
  "shippingAddress": {
    "address": "Adres Bilgileri",
    "contactName": "Arslan Şahin",
    "city": "Bursa",
    "country": "Türkiye"
  },
  "billingAddress": {
    "address": "Adres Bilgileri",
    "contactName": "Arslan Şahin",
    "city": "Bursa",
    "country": "Türkiye"
  },
  "basketItems": [
    {
      "id": "123",
      "price": "2.1",
      "name": "Binocular",
      "category1": "Collectibles",
      "itemType": "PHYSICAL"
    }
  ],
  "currency": "TRY"
}

**Comment by HalilAlgan** [comment]
> callback parametresini ekleyince bu hatayi aldim bende, bunun bi cozumu var mi? 3D kullanmak icin callback parametlesi lazim ama onu ekleyincede calismiyor...

merhaba ayni hatayi ben de aldim simdi. cozebildiniz mi acaba?

**Comment by emirhannaneli** [comment]
UTF-8 yüzünden miş java api sini kullanıyordum localde çalışıyordu ancak sunucuda bu hatayı alıyordum `-Dfile.encoding="UTF-8"`  argümanı ekleyince çözüldü

**Comment by hkarakose** [comment]
Ubuntu sunucudan Amazon Linux'a geçince ben de bu hatayı almaya başladım. Şimdilik Ubuntu'ya geri donduk. Buna benzer bir senaryo ile karşılaşan var mı?

**Comment by hkarakose** [comment]
> dediğim gibi utf 8 unicode biçimini kullanılması gerek

Benim senaryomda işe yaramadı. Aynı release'i, Ubuntu yerine Amazon Linux'a kurmaya başlayınca ortaya cikti.

**Comment by SalihKalender** [comment]
db'den gelen buyer.surname boş string geldiğinden bendede bu hata meydana geldi

**Comment by hasanbaysal** [comment]
aynı hatayı bende aldım gönderdiğiniz apikey ve secret bilgilerini kontrol edin. Asp.net core ile geliştirme yapıyorum appsettings içersine apikey'i kopyala yapıştır yaparken eksik yerleştirmişim. Düzeltince sorun çözüldü
