### ISSUE TITLE
[Request] Disabling the installment per request

### ISSUE THREAD

**Issue by berkayunal** [iyzico/iyzipay-php#6]
Hi,

Do you have plans to disable "Installment" when generating "Checkout Form" by request. This was present in the prior system. Thus enabling us to generate the form with no installment option when needed. The need for disabling the installment may rely on local logic for some merchants. For example in our system there is a configuration for merchants as "Taksitli satış için minumum sepet tutarı". By depending on the local logic and settings for the merchant we were able to generate the "Checkout Form" with no installment option.

Thanks.

**Comment by yyenigun** [comment]
Hi,

This is just a PHP client of our API. So we are collecting requirements about only client side here. Your requirements are about our API, not the client. So can you send an e-mail about your requirements to our integration team? (i.e. emre.findik@iyzico.com) We only accept issues and contributions about client code on Github. We accept issues about the API with our integration team not on Github.

Thanks for your feedbacks.

Yalçın

**Comment by hakanerdogan** [comment]
Additional info:
For New Features & Requirements --> please send email to entegrasyon@iyzico.com address.
Best

@berkayunal @yyenigun @sotuzun
