### ISSUE TITLE
paidPrice BKM Express ile ödemede bulunmuyor

### ISSUE THREAD

**Issue by RaSiM** [iyzico/iyzipay-php#61]
Merhabalar,

Php ile entegrasyonunu yaptım ve kullanıyorum. BKM dökümanında paidPrice olup gönderimi zorunlu denmesine rağmen php kodlarında bunu göremedim. 

Bilgilendirebilir misiniz?

Teşekkürler.

**Comment by sotuzun** [comment]
Merhaba,
paidPrice gönderimi gerekmiyor. Bahsettiğiniz döküman dev.iyzipay.com sitesinde midir?
Teşekkürler

**Comment by RaSiM** [comment]
Aynen oradaymış :)

Normal kullanımı paidprice'a uygun kullandık. Aynı şekilde bkm'de bu neden yok yapılacak mı?

**Comment by sotuzun** [comment]
BKM çalışma mantığına göre yapıldığı için ilk init sırasında paidPrice alınmaya gerek olmuyor. Bunun gibi entegrasyon ile ilgili sorularınızı entegrasyon at iyzico adresine yollayabilirsiniz.
Issue'yu kapatıyorum.
Teşekkürler
