### ISSUE TITLE
Re-record with registered card

### ISSUE THREAD

**Issue by hayreddintuzel** [iyzico/iyzipay-php#67]
Hi, I am trying to create a subscription system with your register card feature. But there are a problem. Your system is trying to re-record the same card even though the card information has already been saved in the system. Can u prevent it?

**Comment by kurtulussahin** [comment]
Hi @hayreddintuzel, our card registiration API dont have same card validation. This is a design decision in our side for the sake of simplicity.
To get more detail, you can drop a ticket from entegrasyon@iyzico.com. 
We want to support you during your integration project.
