### ISSUE TITLE
Composer Empty PSR-4 Namespace Problem

### ISSUE THREAD

**Issue by mahony0** [iyzico/iyzipay-php#73]
Merhaba,
https://github.com/composer/composer/issues/5092 ve https://github.com/briannesbitt/Carbon/issues/1374 konularında tartışılan empty namespace sorununu, biz de iyzipay entegrasyonu ile yaşıyoruz. Laravel tabanlı bir CMS sistemi üzerinde kullandığımız iyzipay-php eklentisinde de PHP kaynaklı empty namespace sorunu bulunuyor.

Bu sorunu composer i aşağıdaki şekilde güncelleyerek çözmek mümkün:
```json
  "autoload": {
    "psr-4": {
      "Iyzipay\\": "src/Iyzipay/"
    }
  },
```
eğer bu düzenleme plugin için uygunsa PR gönderebilirim.
Teşekkürler

**Comment by mahony0** [comment]
Bu kütüphane hala aktif mi?

**Comment by sozgat** [comment]
Merhabalar,

Değerli katkınız için teşekkürler.
