### ISSUE TITLE
All Transactions listeleme

### ISSUE THREAD

**Issue by alikopasa** [iyzico/iyzipay-php#90]
Merhabalar,

All Transactions i listeleyebilecegimiz bir servis varmi acaba?

**Comment by ShopskaSalad** [comment]
Selamlar @alikopasa,
Evet bunu yapabileceğiniz bir servisimiz bulunmaktadır.
Sandbox hesabınızın olduğunu kabul ederek,
İlgili adrese; 
`https://sandbox-api.iyzipay.com/v2/reporting/payment/transactions?transactionDate=2020-12-30&page=1`
GET isteğinde bulunarak o güne ait ödemeleri listeleyebilirsiniz, ödeme çokluğuna bağlı olarakta indexi arttırabilirsiniz.
Bu işlemlerin daha detaylısı içinse admin panel kullanılabilir, ancak servis olarak sorduğunuz için bunu ekliyorum.
Mutlu kodlu yıllar 🎄 :v:

**Comment by ismailua** [comment]
Merhaba bende aynı servisi kullanmak istiyorum ama dönen yanıt her zaman boş oluyor.
https://github.com/iyzico/iyzipay-php/blob/master/samples/retrieve_payout_transactions.php
sanırım aynı servis durumu success olmasına ragmen datalar boş gözükmekte.

Request:
   $options []....
    $request = new \Iyzipay\Request\RetrieveTransactionsRequest();
    $request->setLocale(\Iyzipay\Model\Locale::TR);
    //$request->setConversationId("123456789");
    $request->setDate("2022-12-20 10:00:00");
    $payoutCompletedTransactionList = \Iyzipay\Model\PayoutCompletedTransactionList::retrieve($request, $options);

Response: 
Iyzipay\Model\PayoutCompletedTransactionList Object
(
    [rawResult:Iyzipay\ApiResource:private] => {
  "status" : "success",
  "locale" : "tr",
  "systemTime" : 1671522165855,
  "payoutCompletedTransactions" : [ ]
}
    [status:Iyzipay\IyzipayResource:private] => success
    [errorCode:Iyzipay\IyzipayResource:private] => 
    [errorMessage:Iyzipay\IyzipayResource:private] => 
    [errorGroup:Iyzipay\IyzipayResource:private] => 
    [locale:Iyzipay\IyzipayResource:private] => tr
    [systemTime:Iyzipay\IyzipayResource:private] => 1671522165855
    [conversationId:Iyzipay\IyzipayResource:private] => 
    [payoutCompletedTransactions:Iyzipay\Model\PayoutCompletedTransactionList:private] => Array
        (
        )

)

**Comment by byasarcse** [comment]
Merhabalar,

@ismailua, istek yapısında gönderdiğiniz tarih parametresinde saat değerini 23:59:59 olarak göndererek tekrar denemenizi rica ederiz. 

Sorunun devam etmesi durumunda destek@iyzico.com ile iletişime geçebilirsiniz.

Zaman aşımından konuyu kapatıyoruz.
