### ISSUE TITLE
Geçersiz istek hatası

### ISSUE THREAD

**Issue by fuko93** [iyzico/iyzipay-php#93]
Merhaba ödeme alınırken geçersiz istek hatası veriyor. Hata kodu 11

**Comment by can3ry** [comment]
Furkan Bey selamlar. Geçersiz istek hatası bazı parametrelerin yanlış gönderilmesinden dolayı alınabilir. Mail üzerinden iletişime geçiyorum.

**Comment by fuko93** [comment]
Selamlar giden ve dönen çıktı şu şekilde.

İstek
`object(IyzipayRequestCreatePaymentRequest)#9 (18) {
["price":"IyzipayRequestCreatePaymentRequest":private]=>
float(159.7)
["paidPrice":"IyzipayRequestCreatePaymentRequest":private]=>
float(159.7)
["installment":"IyzipayRequestCreatePaymentRequest":private]=>
int(1)
["paymentChannel":"IyzipayRequestCreatePaymentRequest":private]=>
NULL
["basketId":"IyzipayRequestCreatePaymentRequest":private]=>
NULL
["paymentGroup":"IyzipayRequestCreatePaymentRequest":private]=>
NULL
["paymentCard":"IyzipayRequestCreatePaymentRequest":private]=>
object(IyzipayModelPaymentCard)#10 (9) {
["cardHolderName":"IyzipayModelPaymentCard":private]=>
NULL
["cardNumber":"IyzipayModelPaymentCard":private]=>
NULL
["expireYear":"IyzipayModelPaymentCard":private]=>
NULL
["expireMonth":"IyzipayModelPaymentCard":private]=>
NULL
["cvc":"IyzipayModelPaymentCard":private]=>
NULL
["registerCard":"IyzipayModelPaymentCard":private]=>
NULL
["cardAlias":"IyzipayModelPaymentCard":private]=>
NULL
["cardToken":"IyzipayModelPaymentCard":private]=>
NULL
["cardUserKey":"IyzipayModelPaymentCard":private]=>
NULL
}
["buyer":"IyzipayRequestCreatePaymentRequest":private]=>
object(IyzipayModelBuyer)#11 (13) {
["id":"IyzipayModelBuyer":private]=>
string(3) "11"
["name":"IyzipayModelBuyer":private]=>
string(6) "***"
["surname":"IyzipayModelBuyer":private]=>
string(7) "****"
["identityNumber":"IyzipayModelBuyer":private]=>
string(11) "******"
["email":"IyzipayModelBuyer":private]=>
string(24) "***@**.co"
["gsmNumber":"IyzipayModelBuyer":private]=>
string(13) "******"
["registrationDate":"IyzipayModelBuyer":private]=>
NULL
["lastLoginDate":"IyzipayModelBuyer":private]=>
NULL
["registrationAddress":"IyzipayModelBuyer":private]=>
string(37) "****"
["city":"IyzipayModelBuyer":private]=>
string(8) "Istanbul"
["country":"IyzipayModelBuyer":private]=>
string(6) "Turkey"
["zipCode":"IyzipayModelBuyer":private]=>
NULL
["ip":"IyzipayModelBuyer":private]=>
string(13) "***"
}
["shippingAddress":"IyzipayRequestCreatePaymentRequest":private]=>
object(IyzipayModelAddress)#12 (5) {
["address":"IyzipayModelAddress":private]=>
string(52) "****"
["zipCode":"IyzipayModelAddress":private]=>
string(5) "***"
["contactName":"IyzipayModelAddress":private]=>
string(11) "***"
["city":"IyzipayModelAddress":private]=>
string(9) "İSTANBUL"
["country":"IyzipayModelAddress":private]=>
string(6) "Turkey"
}
["billingAddress":"IyzipayRequestCreatePaymentRequest":private]=>
object(IyzipayModelAddress)#13 (5) {
["address":"IyzipayModelAddress":private]=>
string(52) "***
["zipCode":"IyzipayModelAddress":private]=>
string(5) "***"
["contactName":"IyzipayModelAddress":private]=>
string(11) "***"
["city":"IyzipayModelAddress":private]=>
string(9) "İSTANBUL"
["country":"IyzipayModelAddress":private]=>
string(6) "Turkey"
}
["basketItems":"IyzipayRequestCreatePaymentRequest":private]=>
array(1) {
[0]=>
object(IyzipayModelBasketItem)#14 (8) {
["id":"IyzipayModelBasketItem":private]=>
string(3) "538"
["price":"IyzipayModelBasketItem":private]=>
float(159.7)
["name":"IyzipayModelBasketItem":private]=>
string(6) "Hizmet"
["category1":"IyzipayModelBasketItem":private]=>
string(6) "Hizmet"
["category2":"IyzipayModelBasketItem":private]=>
string(6) "Hizmet"
["itemType":"IyzipayModelBasketItem":private]=>
string(8) "PHYSICAL"
["subMerchantKey":"IyzipayModelBasketItem":private]=>
NULL
["subMerchantPrice":"IyzipayModelBasketItem":private]=>
NULL
}
}
["paymentSource":"IyzipayRequestCreatePaymentRequest":private]=>
NULL
["currency":"IyzipayRequestCreatePaymentRequest":private]=>
string(3) "TRY"
["posOrderId":"IyzipayRequestCreatePaymentRequest":private]=>
NULL
["connectorName":"IyzipayRequestCreatePaymentRequest":private]=>
NULL
["callbackUrl":"IyzipayRequestCreatePaymentRequest":private]=>
NULL
["locale":"IyzipayRequest":private]=>
string(2) "tr"
["conversationId":"IyzipayRequest":private]=>
NULL
}`

Dönen Cevap
`object(stdClass)#15 (5) {
["status"]=>
string(7) "failure"
["errorCode"]=>
string(2) "11"
["errorMessage"]=>
string(15) "Geçersiz istek"
["locale"]=>
string(2) "tr"
["systemTime"]=>
int(1562706996441)
}`

**Comment by fuko93** [comment]
> Furkan Bey selamlar. Geçersiz istek hatası bazı parametrelerin yanlış gönderilmesinden dolayı alınabilir. Rica etsem mail veya telefonunuzu paylaşır mısınız? Detaylar için iletişime geçelim.
> Teşekkürler.
Selam,
Mail adresim f.damar@hotmail.com
Numaram 05314570170

**Comment by tpaksu** [comment]
@fuko93 nasıl çözdüğünü hatırlıyor musun? Ben de aynı hatayla karşılaşıyorum ve çözemedim iki gündür.

**Comment by sanalisci** [comment]
Sağol
